import type { Metadata } from 'next';
import Header from './components/common/Header';
import './styles/common/globals.scss';
import style from './styles/common/layout.module.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className={style['main']}>{children}</main>
      </body>
    </html>
  );
}
